version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "japer-technology"
    assignees:
      - "japer-technology"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Enable version updates for npm in examples/node
  - package-ecosystem: "npm"
    directory: "/examples/node"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "japer-technology"
    assignees:
      - "japer-technology"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "japer-technology"
    assignees:
      - "japer-technology"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"